# Generated by Django 5.1.5 on 2025-01-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInput",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sleep", models.DateTimeField(null=True)),
                ("wake", models.DateTimeField(null=True)),
                ("sunlight_start", models.DateTimeField(null=True)),
                ("sunlight_end", models.DateTimeField(null=True)),
                ("exercise_start", models.DateTimeField(null=True)),
                ("exercise_end", models.DateTimeField(null=True)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[("strength", "Strength"), ("cardio", "Cardio")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("caffeine_intake", models.DateTimeField(null=True)),
            ],
        ),
    ]
